# golangci-lint 配置
# 文档: https://golangci-lint.run/usage/configuration/
version: "2"
run:
  timeout: 5m
  tests: true
  # modules-download-mode: readonly

output:
  formats:
    text:
      path: stdout
      colors: true
      print-issued-lines: true
      print-linter-name: true
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      # Simplify code: gofmt with `-s` option.
      # Default: true
      simplify: true
linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - gosec
    - gocritic
  settings:
    errcheck:
      check-blank: true
      check-type-assertions: true
    misspell:
      locale: US

 

